version: '3.7'
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  sidekiq-ui:
    build: .
    depends_on:
      - redis
    ports:
      - 9292:9292
    volumes:
      - .:/app
    env_file: .env.dev
    command: bundle exec rackup -o 0.0.0.0 -p 9292

  sidekiq-worker:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file: .env.dev
    command: bundle exec sidekiq -r ./lib/fortune.rb

  wiseman:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file: .env.dev
    command: bundle exec ruby -Ilib ./lib/wiseman.rb

